set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports led_out]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN T5 [get_ports clk]
set_property PACKAGE_PIN K2 [get_ports led_out]
set_property PACKAGE_PIN P15 [get_ports rst]
